version: '3.8'

services:
  yoga-bot:
    build: .
    container_name: yoga-telegram-bot
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs  # Для логов (опционально)
    environment:
      - TZ=Europe/Moscow  # Установите свой часовой пояс
      - PYTHONUNBUFFERED=1
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge